<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:type" content="website">
    <link rel="icon" href="/assets/images/tads-favicon.png" type="image/png">
    <link rel="stylesheet" type="text/css"
                           href="/assets/css/styles.css">
    <title></title>
    <meta property="og:title" content=
    "">
    <meta name="description" content="">
    <meta property="og:description" content="">
</head>
<header id="header"><div class="header-search">
    <form class="header-search-form" action="/search" method="get">
      <input type="text" id="search-box" name="query">
      <input type="submit" value="search">
    </form>
  </div>  </header>
<body>
<main id="content">
<p><img src="topbar.jpg" data-border="0" />
<a href="toc.html" class="nav">Table of Contents</a> |
<a href="langsec.html" class="nav">The Language</a> &gt; Exceptions and
Error Handling<br />
<span class="navnp"><a href="namedargs.html" class="nav"><em>Prev:</em> Named Arguments</a>
   
<a href="anonfn.html" class="nav"><em>Next:</em> Anonymous Functions</a>
    </span></p>
<h1 id="exceptions-and-error-handling">Exceptions and Error Handling</h1>

<p>TADS 3 provides a “structured exception handling” mechanism, which lets
the program to signal and handle unusual conditions in a structured
manner. TADS 3 exceptions work very much like Java exceptions, so if
you’ve used Java you’ll find the TADS 3 exception mechanism familiar.</p>

<p>Conceptually, an exception is any unusual condition. Exceptions usually
indicate errors, but they don’t have to; they can also be used for a
variety of other purposes, such as terminating a procedure early or
recovering from a resource shortage. An exception is represented by an
object; you can tell what kind of exception you have by looking at the
class of the exception object. Exception objects are the same as any
other objects, so you can create as many different types of exception
classes as you need.</p>

<p>Exception handling has two components: “throwing” and “catching.”</p>

<p>When something unusual occurs in your program that you wish to handle
using the exception mechanism, you “throw an exception.” This means that
you create a new object to describe the unusual condition or error, then
use the <code class="language-plaintext highlighter-rouge">throw</code> statement to throw the
exception. The <code class="language-plaintext highlighter-rouge">throw</code> statement is a little
like <code class="language-plaintext highlighter-rouge">return</code> or <code class="language-plaintext highlighter-rouge">goto</code>,
in that it abruptly transfers execution somewhere else; hence any
statement immediately following a <code class="language-plaintext highlighter-rouge">throw</code> is
unreachable (unless, of course, it can be reached by a label or some
other means that doesn’t involve going through the
<code class="language-plaintext highlighter-rouge">throw</code> statement).</p>

<p>Where does <code class="language-plaintext highlighter-rouge">throw</code> send execution? This is where
“catching” comes in. When you throw an exception, the VM looks for an
enclosing block of code protected within a <code class="language-plaintext highlighter-rouge">try</code>
block. This search is done according to the “call chain” - the series of
function and method calls that have been made so far to reach the
current point in the code. The VM looks for the nearest enclosing
<code class="language-plaintext highlighter-rouge">try</code> statement in the call chain - this might
be in the current method, actually enclosing the code with the
<code class="language-plaintext highlighter-rouge">throw</code>, or it might be in one of the callers.
The VM searches outward from the current method.</p>

<p>When the VM finds the first enclosing <code class="language-plaintext highlighter-rouge">try</code>
statement, it looks at the statement’s <code class="language-plaintext highlighter-rouge">catch</code>
clauses. If there’s a <code class="language-plaintext highlighter-rouge">catch</code> for a superclass
of the thrown exception, the VM transfers control to the code within
that <code class="language-plaintext highlighter-rouge">catch</code> clause’s handler block; otherwise,
the VM skips that <code class="language-plaintext highlighter-rouge">try</code> and continues searching
for the next enclosing <code class="language-plaintext highlighter-rouge">try</code>.</p>

<p>For each <code class="language-plaintext highlighter-rouge">try</code> statement that encloses the
current code but doesn’t define a <code class="language-plaintext highlighter-rouge">catch</code> block
for the thrown exception, the VM checks to see if the
<code class="language-plaintext highlighter-rouge">try</code> has an associated
<code class="language-plaintext highlighter-rouge">finally</code> block, and executes the enclosed code
before looking for an enclosing <code class="language-plaintext highlighter-rouge">try</code> block.</p>

<p>If the VM searches the entire call stack without finding any enclosing
<code class="language-plaintext highlighter-rouge">try</code> block with a
<code class="language-plaintext highlighter-rouge">catch</code> for the thrown exception, the VM
terminates the program. If it has to do this, the VM checks the
<code class="language-plaintext highlighter-rouge">exceptionMessage</code> property of the unhandled
exception object, and displays the value of that property if it’s a
(single-quoted) string value. This at least lets the user see a message
describing the error that forced the program to terminate.</p>

<p>A <code class="language-plaintext highlighter-rouge">try</code> statement looks like this:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>    try
    {
      // some code that might throw an exception, or call
      // a function or method that might do so
    }
    catch (FirstExceptionClass exc1)
    {
      // handle FirstExceptionClass exceptions
      // exc1 is a local with the thrown exception object
    }
    catch (SecondExceptionClass exc2)
    {
      // handle SecondExceptionClass exceptions
      // exc2 is a local with the thrown exception object
    }
    finally
    {
      // do some cleanup work  this gets called
      // whether an exception occurs or not
    }
</code></pre></div></div>

<p>A <code class="language-plaintext highlighter-rouge">try</code> statement can have as many
<code class="language-plaintext highlighter-rouge">catch</code> clauses as needed – it can even have no
<code class="language-plaintext highlighter-rouge">catch</code> clauses at all. The
<code class="language-plaintext highlighter-rouge">finally</code> clause is optional, but only one is
allowed if it’s present at all, and it must follow all of the
<code class="language-plaintext highlighter-rouge">catch</code> clauses.</p>

<p>Each <code class="language-plaintext highlighter-rouge">catch</code> clause has a name following the
name of the exception. The <code class="language-plaintext highlighter-rouge">catch</code> defines a new
local variable with the given name – the variable is local to the code
within the <code class="language-plaintext highlighter-rouge">catch</code> clause. When the exception is
caught, the VM will store a reference to the thrown exception object in
this variable; this is, of course, the same object that was used in the
<code class="language-plaintext highlighter-rouge">throw</code> statement that threw the exception in
the first place.</p>

<p>The VM searches for a <code class="language-plaintext highlighter-rouge">catch</code> clause that
matches the exception class starting with the first
<code class="language-plaintext highlighter-rouge">catch</code> associated with the
<code class="language-plaintext highlighter-rouge">try</code>, and considers each
<code class="language-plaintext highlighter-rouge">catch</code> in turn until it finds a match. A
<code class="language-plaintext highlighter-rouge">catch</code> matches if the named class is a
superclass of the exception behing handled. Because the
<code class="language-plaintext highlighter-rouge">catch</code> clauses are tried in order, you can have
one handler for a specific type of exception, and also have a later
handler for a superclass of the first exception; the specific type will
be handled by the first handler, since the VM will find that handler
earlier than the more general handler. In such cases, only the first
matching handler will be invoked.</p>

<p>If a <code class="language-plaintext highlighter-rouge">finally</code> clause is present, the VM will
always execute the code contained within, no matter how control leaves
the <code class="language-plaintext highlighter-rouge">try</code> block. If control leaves via an
exception that isn’t handled by any of the <code class="language-plaintext highlighter-rouge">try</code>
statement’s <code class="language-plaintext highlighter-rouge">catch</code> clauses, the VM will execute
the <code class="language-plaintext highlighter-rouge">finally</code> code before it continues the
search for the next enclosing <code class="language-plaintext highlighter-rouge">try</code>. If no
exceptions occur, so control leaves the <code class="language-plaintext highlighter-rouge">try</code>
block normally, the <code class="language-plaintext highlighter-rouge">finally</code> code is executed
immediately after the last statement in the main
<code class="language-plaintext highlighter-rouge">try</code> block. If an exception is thrown but one
of the <code class="language-plaintext highlighter-rouge">try</code> statement’s
<code class="language-plaintext highlighter-rouge">catch</code> clauses catches the exception, the VM
executes the <code class="language-plaintext highlighter-rouge">finally</code> code immediately after
the last statement in the <code class="language-plaintext highlighter-rouge">catch</code> block (or, if
control is transfered out of the <code class="language-plaintext highlighter-rouge">catch</code> block
in some other way - <code class="language-plaintext highlighter-rouge">goto</code>,
<code class="language-plaintext highlighter-rouge">return</code>, <code class="language-plaintext highlighter-rouge">throw</code>,
etc. - the <code class="language-plaintext highlighter-rouge">finally</code> is executed just before
that control transfer).</p>

<p>Note that the code in a <code class="language-plaintext highlighter-rouge">finally</code> clause will
execute <em>no matter how execution leaves the
<code class="language-plaintext highlighter-rouge">try</code> block</em>. This even includes
<code class="language-plaintext highlighter-rouge">goto</code>, <code class="language-plaintext highlighter-rouge">return</code>,
<code class="language-plaintext highlighter-rouge">break</code>, and <code class="language-plaintext highlighter-rouge">continue</code>
statements. If the <code class="language-plaintext highlighter-rouge">try</code> block contains a
<code class="language-plaintext highlighter-rouge">return</code> statement, the program will first
calculate the value of the expression being returned (if any), then it
will execute the <code class="language-plaintext highlighter-rouge">finally</code> code, and only then
will control transfer back to the caller of the current function or
method. (It’s important that the return value is calculated first,
because it counts as code that’s protected by the
<code class="language-plaintext highlighter-rouge">try</code>. If an exception is thrown while
calculating that value, it’ll be handled the same as any other exception
thrown inside the <code class="language-plaintext highlighter-rouge">try</code>.) If you use
<code class="language-plaintext highlighter-rouge">goto</code>, <code class="language-plaintext highlighter-rouge">break</code>, or
<code class="language-plaintext highlighter-rouge">continue</code> within the
<code class="language-plaintext highlighter-rouge">try</code> block to jump to a statement that’s
outside the <code class="language-plaintext highlighter-rouge">try</code> block, the program will
execute the <code class="language-plaintext highlighter-rouge">finally</code> code just before jumping
to the target statement.</p>

<p>Here’s an example that illustrates how all of this works.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>    #include "tads.h"

    class ResourceError: Exception;
    class ParsingError: Exception;

    main(args)
    {
      a();
    }

    a()
    {
      b(1);
      b(2);
      b(3);
    }

    b(x)
    {
      "This is b(&lt;&lt;x&gt;&gt;)\n";
      try
      {
        c(x);
      }
      catch (Exception exc)
      {
        "b: Caught an exception: &lt;&lt;exc.exceptionMessage&gt;&gt;\n";
      }
      "Done with b(&lt;&lt;x&gt;&gt;)\n";
    }

    c(x)
    {
      "This is c(&lt;&lt;x&gt;&gt;)\n";
      try
      {
        d(x);
      }
      catch(ParsingError perr)
      {
        "c: Caught a parsing error: &lt;&lt;perr.exceptionMessage&gt;&gt;\n";
      }
      finally
      {
        "In c's finally clause\n";
      }
      "Done with c(&lt;&lt;x&gt;&gt;)\n";
    }

    d(x)
    {
      "This is d(&lt;&lt;x&gt;&gt;)\n";
      e(x);
      "Done with d(&lt;&lt;x&gt;&gt;)\n";
    }

    e(x)
    {
      "This is e(&lt;&lt;x&gt;&gt;)\n";
      if (x == 1)
      {
        "Throwing resource error...\n";
        throw new ResourceError('some resource error');
      }
      else if (x == 2)
      {
        "Throwing parsing error...\n";
        throw new ParsingError('some parsing error');
      }
      "Done with e(&lt;&lt;x&gt;&gt;)\n";
    }
</code></pre></div></div>

<p>When this program is run, it will show the following output:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>    This is b(1)
    This is c(1)
    This is d(1)
    This is e(1)
    Throwing resource error...
    In c's finally clause
    b:  Caught an exception:  some resource error
    Done with b(1)
    This is b(2)
    This is c(2)
    This is d(2)
    This is e(2)
    Throwing parsing error...
    c:  Caught a parsing error:  some parsing error
    In c's finally clause
    Done with c(2)
    Done with b(2)
    This is b(3)
    This is c(3)
    This is d(3)
    This is e(3)
    Done with e(3)
    Done with d(3)
    In c's finally clause
    Done with c(3)
    Done with b(3)
</code></pre></div></div>

<p>This illustrates several aspects of exceptions.</p>

<p>First, note that function <code class="language-plaintext highlighter-rouge">d()</code> doesn’t have any
exception handlers (i.e., it has no <code class="language-plaintext highlighter-rouge">try</code>
block). Since this function is not concerned with catching any
exceptions that occur within itself or functions it calls, it doesn’t
need any exception handlers. This is one of the advantages of exceptions
over using return codes to indicate errors: intermediate routines that
don’t care about exceptions don’t need to include any code to check for
them. When searching for a <code class="language-plaintext highlighter-rouge">try</code> block, the VM
simply skips function <code class="language-plaintext highlighter-rouge">d()</code> if it’s in the call
chain, since it has no handlers.</p>

<p>Second, note that function <code class="language-plaintext highlighter-rouge">c()</code> only handles
ParsingError exceptions. Since this function has no handlers for any
other exception types, the VM skips past this function when trying to
find a handler for the <code class="language-plaintext highlighter-rouge">ResourceError</code>
exception. So, not only can a function ignore exceptions entirely, but
it can selectively include handlers only for the specific exceptions it
wants to handle, and ignore anything else.</p>

<p>Third, note that, once an exception is caught, it no longer disrupts the
program’s control flow. In other words, an exception isn’t “re-thrown”
after it’s caught, unless you explicitly throw it again with another
<code class="language-plaintext highlighter-rouge">throw</code> statement in the handler that caught it.</p>

<h2 id="handling-vm-run-time-errors">Handling VM Run-Time Errors</h2>

<p>When your program does something illegal, such as trying to multiple two
strings together or extracting an element from a list at an invalid
index, a run-time error occurs. TADS 3 treats all run-time errors as
ordinary exceptions; this means that you can handle run-time errors
using the same try/catch mechanism that you use to handle your own
exceptions.</p>

<p>The system library defines the <code class="language-plaintext highlighter-rouge">RuntimeError</code>
class, which serves as the base class for all VM run-time errors.</p>

<p>When a VM run-time error occurs, the VM create and throws a new
<code class="language-plaintext highlighter-rouge">RuntimeError</code> instance. The
<code class="language-plaintext highlighter-rouge">errno\_</code> property of this object is set to the
VM error number describing the error that occurred, and the
<code class="language-plaintext highlighter-rouge">exceptionMessage</code> property is set to the VM
error text for the error. You can inspect these properties directly, but
if you just want to display the error message, you should call the
<code class="language-plaintext highlighter-rouge">displayException()</code> method of the error object.</p>

<hr />

<p><em>TADS 3 System Manual</em><br />
<a href="toc.html" class="nav">Table of Contents</a> |
<a href="langsec.html" class="nav">The Language</a> &gt; Exceptions and
Error Handling<br />
<span class="navnp"><a href="namedargs.html" class="nav"><em>Prev:</em> Named Arguments</a>
   
<a href="anonfn.html" class="nav"><em>Next:</em> Anonymous Functions</a>
    </span></p>


</main>
<footer id="footer">
    <p>This is an unofficial informational website to aggregate TADS 3 information and does not claim authorship over, or any rights to, TADS 3 itself. All resources copyright their credited owners. TADS itself is <a href="https://www.tads.org/copyright.htm">Copyright ©2001-2013 Michael J. Roberts</a>.</p>
    <p><a href="/">Back to Homepage</a></p>
</footer>
</body>
</html>

<script>
    if(window.location !== window.top.location) {
        let header = document.getElementById('header');
        let footer = document.getElementById('footer');
        header.remove();
        footer.remove();
    }
</script>